### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by DenisSergeevitch** [mwarzynski/tax_stocks#4]
Hello, thank you for the helpful tool!
When I'm trying to use it, I'm getting an error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte`

I have tried to fix it by converting CSV to ISO-8859-1 and by editing line 33 of _revolut.py_ like that:
```
        with open(file_name, "r", newline='', encoding='ISO-8859-1', errors='replace') as f:
            reader = csv.reader(f, delimiter=',')
```
But I still get an error after that fix:

```
Traceback (most recent call last):
  File "tax_stocks/main.py", line 44, in <module>
    main()
  File "tax_stocks/main.py", line 25, in main
    transactions += provider.provide()
  File "tax_stocks/app/providers/revolut.py", line 24, in provide
    transactions += self._provide_for_file(join(self.folder, file))
  File "tax_stocks/app/providers/revolut.py", line 33, in _provide_for_file
    next(reader)  # skip header row (which contains description of columns)
_csv.Error: line contains NUL

```

Could you please point me where to look for an error?

**Comment by mwarzynski** [comment]
> thank you for the helpful tool!

You're welcome!
(Please remember I do not give any assurance about the correctness of this application -- see the disclaimer in the README.)

---

Why did you set `newline=''` parameter? In addition, I wouldn't recommend using `errors='replace'` as we would rather want to know if something went wrong during the read process (i.e. we don't want to have `?` character in random places).

---

If you get `line contains NULL` exception, then it seems the script tries to open an invalid file. Assumption about the first line being a header is hardcoded in the code (and this is where you get an exception). At least, this would be my take. I admit, I didn't try to reproduce it.

Could you please make sure that the `data/investing/revolut/` folder contains only valid CSV files?

Here is an example how valid CSV looks like:
```
$ head data/investing/revolut/2021.csv
Date,Ticker,Type,Quantity,Price per share,Total Amount,Currency,FX Rate
01/01/2021 15:40:21,AAPL,SELL,1,131,400,USD,0.2713
```

I made the numbers up, but the format should be correct (at least as an example). Of course, there should be significantly more rows which represent the transactions (unless you did only one throughout the whole year). Also note that the first line is a header, so that's why we skip it by `next(reader)`.

Regarding the encoding, I would suggest using the UTF-8. It should be simpler to use the file encoding as UTF-8 rather than modify the source code. Support for multiple encodings would be nice though.

**Comment by DenisSergeevitch** [comment]
Thank you for your answer, [Mateusz Warzyński](https://github.com/mwarzynski). 

I have decided to try it again, but now it looks like I have a different problem.

Here is my data structure which I have double-checked and converted again after the issue above, data should be fine now:
```
$ head data/investing/revolut/2021.csv
Date,Ticker,Type,Quantity,Price per share,Total Amount,Currency,FX Rate
12/01/2021 08:28:33,MRK,DIVIDEND,,,$0.55,USD,0.27
28/01/2021 14:56:31,MSFT,TRADE - MARKET,2,$236.16,$472.30,USD,0.27
28/01/2021 14:57:08,MRK,TRADE - MARKET,1,$77.62,$77.61,USD,0.27
28/01/2021 16:14:26,TTWO,TRADE - MARKET,2.6,$202.38,$526.19,USD,0.27
29/01/2021 14:32:36,AAL,TRADE - MARKET,46,$18.68,$859.25,USD,0.27
29/01/2021 14:33:38,AAPL,TRADE - MARKET,10.39495352,$135.70,"$1,410.56",USD,0.27
29/01/2021 14:33:49,NVAX,TRADE - MARKET,10,$190,"$1,899.95",USD,0.27
29/01/2021 14:44:43,PFE,TRADE - MARKET,12.82051282,$36.75,$471.13,USD,0.27
29/01/2021 14:32:59,TTWO,TRADE - MARKET,2.6,$198.79,$516.83,USD,0.27
etc.
```

But error now is different:
```
$python main.py 2021

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 32, in main
    transactions += provider.provide_transactions()
  File "/content/tax_stocks/app/providers/revolut.py", line 36, in provide_transactions
    transactions += self._provide_transactions_from(join(self.folder, file))
  File "/content/tax_stocks/app/providers/revolut.py", line 89, in _provide_transactions_from
    amount = Decimal(row[5])
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

This makes me think that the problem could be with a `DIVIDEND` type of transaction, which contains empty fields; Is this could be a case?

**Comment by DenisSergeevitch** [comment]
Oh, silly me, sorry :) I have found a mistake: 

The data format should be:
`...236.16,472.30,USD,0.27...`

Instead of:
`...$236.16,$472.30,USD,0.27...`

Everything is working perfectly now! Thank you for the repo 🤍
